services:
  - type: web
    name: skincare-ingredient-scout-api
    runtime: python3
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd api && python3 main.py
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.11.0
